/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.puntofuncion;

import javax.swing.JFrame;
import sql.ConexionSql;
import vistas.casouso.FormPrincipal;

/**
 *
 * @author Mari
 */
public class Conectar extends javax.swing.JFrame {

    /**
     * Creates new form Conectar
     */
    public Conectar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncerrarventana = new javax.swing.JButton();
        btnpuntofuncion = new javax.swing.JButton();
        btnCU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncerrarventana.setBackground(new java.awt.Color(204, 255, 255));
        btncerrarventana.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        btncerrarventana.setText("Salir");
        btncerrarventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarventanaActionPerformed(evt);
            }
        });

        btnpuntofuncion.setBackground(new java.awt.Color(204, 255, 255));
        btnpuntofuncion.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        btnpuntofuncion.setText("Punto de Funcion");
        btnpuntofuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntofuncionActionPerformed(evt);
            }
        });

        btnCU.setBackground(new java.awt.Color(204, 255, 255));
        btnCU.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        btnCU.setText("Punto de Caso de Uso");
        btnCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpuntofuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncerrarventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnpuntofuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btncerrarventana)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ConexionSql con = new ConexionSql();
    private void btnCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUActionPerformed
       con.conectar();
        String title = "Caso de Uso";
        FormPrincipal cu = new FormPrincipal ();
        cu.setDefaultCloseOperation(java.awt.Frame.ICONIFIED);
        cu.setResizable(true);
        cu.setTitle(title);
        cu.setLocationRelativeTo(null);
        cu.setVisible(true);
    }//GEN-LAST:event_btnCUActionPerformed

    private void btnpuntofuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntofuncionActionPerformed
        String title = "Punto de Función";
        FormPuntosDeFuncion pf = new FormPuntosDeFuncion (this,false);
        pf.setDefaultCloseOperation(JFrame.ICONIFIED);
        pf.setModal(true);
        pf.setResizable(true);
        pf.setTitle(title);
        pf.setLocationRelativeTo(null);
        pf.setVisible(true);
      
      
    }//GEN-LAST:event_btnpuntofuncionActionPerformed

    private void btncerrarventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarventanaActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btncerrarventanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException  ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conectar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCU;
    private javax.swing.JButton btncerrarventana;
    private javax.swing.JButton btnpuntofuncion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
