/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.puntofuncion;

/**
 *
 * @author Mari
 */
import classes.Complejidad;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sql.ConexionSql;


public class FormPuntosDeFuncion extends javax.swing.JDialog {

    transient ArrayList<Complejidad> lista  = new ArrayList<>();
    /**
     * Creates new form puntofuncion
     */
     public FormPuntosDeFuncion() {
        super();
        initComponents();
    }
    
    public FormPuntosDeFuncion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOK1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        EIComboBox = new javax.swing.JComboBox<>();
        complejidad = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        btnCalculo = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cmbComponente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        btnOK1.setBackground(new java.awt.Color(255, 255, 255));
        btnOK1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EIComboBox.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        EIComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        EIComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(EIComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, 40));

        complejidad.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        complejidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        complejidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complejidadActionPerformed(evt);
            }
        });
        jPanel1.add(complejidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 40));

        valor.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 69, 39));

        btnCalculo.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculo.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCalculo.setText("Calcular");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 133, 41));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 120, 40));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 120, 40));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        cmbComponente.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cmbComponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EI", "EO", "EQ", "ILF", "EIF" }));
        cmbComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComponenteActionPerformed(evt);
            }
        });
        jPanel1.add(cmbComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(700, 800));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 530, 250));

        btnOK.setBackground(new java.awt.Color(255, 255, 255));
        btnOK.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 80, -1, 41));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Complejidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 40));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Valor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Componente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 139, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EIComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIComboBoxActionPerformed
      ConexionSql con = new ConexionSql();
      con.conectar();
      
         try {              
              complejidad.setText(con.consultarComplejidad(cmbComponente.getSelectedItem().toString(), EIComboBox.getSelectedItem().toString()));
         } catch (SQLException ex) {
             Logger.getLogger(FormPuntosDeFuncion.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_EIComboBoxActionPerformed
    
    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
        FormCalculo cal = new FormCalculo(lista);
        String title ="Calcular Punto de Función"; 
        cal.setDefaultCloseOperation(JFrame.ICONIFIED);
        cal.setModal(true);
        cal.setResizable(false);
        cal.setTitle(title);
        cal.setLocationRelativeTo(null);
        cal.setVisible(true);
    }//GEN-LAST:event_btnCalculoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.limpiar();
        this.jTextArea1.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
          this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbComponenteActionPerformed

    public void limpiar (){
        this.cmbComponente.setSelectedItem(0);
        this.valor.setText(null);
        this.EIComboBox.setSelectedItem(0);
        this.complejidad.setText(null);
    }
  
    
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        if ( !"".equals(cmbComponente.getSelectedItem().toString()) && !"".equals(valor.getText()) && !"".equals(complejidad.getText()) ){
            
            jTextArea1.append(cmbComponente.getSelectedItem().toString() + ": " + valor.getText() + " x " + complejidad.getText() +"\n");
            
            String tipo = cmbComponente.getSelectedItem().toString();
            int v = Integer.parseInt(valor.getText());
            int comp = Integer.parseInt(complejidad.getText());
            
            Complejidad c = new Complejidad(tipo,v,comp);
            lista.add(c);
                      
            this.limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los valores", "Atención", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } 

      
    }//GEN-LAST:event_btnOKActionPerformed
   
    private void complejidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complejidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complejidadActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
    }//GEN-LAST:event_btnOK1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException  ex) {
            java.util.logging.Logger.getLogger(FormPuntosDeFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPuntosDeFuncion dialog = new FormPuntosDeFuncion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EIComboBox;
    private javax.swing.JButton btnCalculo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbComponente;
    private javax.swing.JTextField complejidad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
