/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

import classes.Factor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql.conexionsql;

/**
 *
 * @author Mari
 */
public class frm_actores extends javax.swing.JInternalFrame {

    ArrayList<Factor> lista  = new ArrayList<>();
    Integer casoDeUsoSinAjustar = 0;
    conexionsql con2 = new conexionsql();
    
    public frm_actores() {
        initComponents();
        con2.conectarCU();
        
    }
    
    public Integer getValorCasoDeUsoSinAjustar()
    {
        return casoDeUsoSinAjustar;
    }
  
    private void limpiar() {
        cmbActor.setSelectedItem(0);
        textValor.setText(null);
        txtActor.setText(null);
    }
   public void CalcularResultado(){
     int multiplicacion;
        
       int val;
       int fact;
       multiplicacion = 0;
       casoDeUsoSinAjustar = 0;
       for (int i=0; i < lista.size(); i++){
          
           
           val =lista.get(i).getValor(); 
           fact = lista.get(i).getFactor();
           
           multiplicacion = val * fact;
           
           jTextArea1.append("\n");
           jTextArea1.append(lista.get(i).getTipo() + ": " + val + " x " + fact + " = " + multiplicacion + "\n");
           
           casoDeUsoSinAjustar = casoDeUsoSinAjustar + multiplicacion;
       }
        jTextArea1.append("TOTAL: " + casoDeUsoSinAjustar);
        lista.clear();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbActor = new javax.swing.JComboBox<>();
        txtActor = new javax.swing.JTextField();
        textValor = new javax.swing.JTextField();
        btnCalculo = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(205, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factor de pesos de actores sin ajustar (UAW)");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbActor.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cmbActor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Medio", "Complejo" }));
        cmbActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActorActionPerformed(evt);
            }
        });
        jPanel1.add(cmbActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, 40));

        txtActor.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtActor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActorActionPerformed(evt);
            }
        });
        jPanel1.add(txtActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 40));

        textValor.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 69, 39));

        btnCalculo.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculo.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCalculo.setText("Calcular");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 133, 41));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 120, 40));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 120, 40));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(700, 800));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 530, 250));

        btnOK.setBackground(new java.awt.Color(255, 255, 255));
        btnOK.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 80, -1, 41));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Factor");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, 40));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad de actores");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActorActionPerformed
         try {              
              txtActor.setText(con2.consultarActor(cmbActor.getSelectedItem().toString()));
         } catch (SQLException ex) {
             Logger.getLogger(frm_actores.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_cmbActorActionPerformed

    private void txtActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActorActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
       if ( !"".equals(cmbActor.getSelectedItem().toString()) && !"".equals(textValor.getText()) && !"".equals(txtActor.getText()) ){
            
            jTextArea1.append(cmbActor.getSelectedItem().toString() + ": " + textValor.getText() + " x " + txtActor.getText() +"\n");
            
            String tipo = cmbActor.getSelectedItem().toString();
            int v = Integer.parseInt(textValor.getText());
            int f = Integer.parseInt(txtActor.getText());
           
            Factor factor = new Factor (tipo,v,f);
            lista.add(factor);
                     
            this.limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los valores", "Atención", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } 
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
       CalcularResultado();
    }//GEN-LAST:event_btnCalculoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.limpiar();
        jTextArea1.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbActor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textValor;
    private javax.swing.JTextField txtActor;
    // End of variables declaration//GEN-END:variables


}
