/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

/**
 *
 * @author Mari
 */
public class frm_principal extends javax.swing.JFrame {

    frm_actores ventana1;
    frm_peso_cu ventana2;
    frm_punto_cu ventana3;
    frm_complejidad_tecnica ventana4;
    frm_complejidad_ambiental ventana5;
    frm_cu_ajustado ventana6;
    frm_esfuerzo ventana7;
    
    /**
     * Creates new form frm_casouso
     */
    public frm_principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemUAW = new javax.swing.JMenuItem();
        itemUUCW = new javax.swing.JMenuItem();
        itemUUCP = new javax.swing.JMenuItem();
        itemTCF = new javax.swing.JMenuItem();
        itemEF = new javax.swing.JMenuItem();
        itemUCP = new javax.swing.JMenuItem();
        itemE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jMenu1.setText("Punto de Caso de Uso");
        jMenu1.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N

        itemUAW.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemUAW.setText("1. Factor de peso de actores sin ajustar (UAW)");
        itemUAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUAWActionPerformed(evt);
            }
        });
        jMenu1.add(itemUAW);

        itemUUCW.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemUUCW.setText("2. Factor de peso CU sin ajustar (UUCW)");
        itemUUCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUUCWActionPerformed(evt);
            }
        });
        jMenu1.add(itemUUCW);

        itemUUCP.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemUUCP.setText("3. Punto de Caso de uso sin ajustar (UUCP)");
        itemUUCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUUCPActionPerformed(evt);
            }
        });
        jMenu1.add(itemUUCP);

        itemTCF.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemTCF.setText("4. Factores  de Complejidad Técnica (TCF)");
        itemTCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTCFActionPerformed(evt);
            }
        });
        jMenu1.add(itemTCF);

        itemEF.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemEF.setText("5. Factores de Complejidad Ambiental (EF)");
        itemEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEFActionPerformed(evt);
            }
        });
        jMenu1.add(itemEF);

        itemUCP.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemUCP.setText("6. Punto de Caso de Uso Ajustados (UCP)");
        itemUCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUCPActionPerformed(evt);
            }
        });
        jMenu1.add(itemUCP);

        itemE.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        itemE.setText("7. Esfuerzo horas-hombre (E)");
        itemE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEActionPerformed(evt);
            }
        });
        jMenu1.add(itemE);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUAWActionPerformed
        ventana1 = new frm_actores();
        escritorio.add(ventana1);
        ventana1.show();
    }//GEN-LAST:event_itemUAWActionPerformed

    private void itemUUCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUUCWActionPerformed
        ventana2 = new frm_peso_cu();
        escritorio.add(ventana2);
        ventana2.show();            
    }//GEN-LAST:event_itemUUCWActionPerformed

    private void itemUUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUUCPActionPerformed
        ventana3 = new frm_punto_cu(ventana1.getValorCasoDeUsoSinAjustar(), ventana2.getValorCuSinAjustar());
        escritorio.add(ventana3);
        ventana3.show();
    }//GEN-LAST:event_itemUUCPActionPerformed

    private void itemTCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTCFActionPerformed
        ventana4 = new frm_complejidad_tecnica();
        escritorio.add(ventana4);
        ventana4.show();
    }//GEN-LAST:event_itemTCFActionPerformed

    private void itemEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEFActionPerformed
        ventana5 = new frm_complejidad_ambiental();
        escritorio.add(ventana5);
        ventana5.show();
    }//GEN-LAST:event_itemEFActionPerformed

    private void itemUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUCPActionPerformed
        //frm_cu_ajustado ventana6 = new frm_cu_ajustado();
        ventana6 = new frm_cu_ajustado(ventana3.getSuma(), ventana4.getTCF() , ventana5.getEF());
        escritorio.add(ventana6);
        ventana6.show();
    }//GEN-LAST:event_itemUCPActionPerformed

    private void itemEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEActionPerformed
        //frm_esfuerzo ventana7 = new frm_esfuerzo();
        //escritorio.add(ventana7);
        //ventana7.show();
    }//GEN-LAST:event_itemEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemE;
    private javax.swing.JMenuItem itemEF;
    private javax.swing.JMenuItem itemTCF;
    private javax.swing.JMenuItem itemUAW;
    private javax.swing.JMenuItem itemUCP;
    private javax.swing.JMenuItem itemUUCP;
    private javax.swing.JMenuItem itemUUCW;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
