/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

import classes.Peso;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.conexionsql;

/**
 *
 * @author Cristian
 */
public class frm_complejidad_ambiental extends javax.swing.JInternalFrame {

    conexionsql con2 = new conexionsql();
    ArrayList<Peso> listaPeso  = new ArrayList<>();
    ArrayList<Integer> listaValor = new ArrayList<>();
    float eFactor;
    float EF;
    
    public frm_complejidad_ambiental() {
        initComponents();
        con2.conectarCU();
    }

    public float getEF() {
        return EF;
    }

    public void setEF(float EF) {
        this.EF = EF;
    }
    
    public void agregarLista(String tipo, float peso){
       Peso p = new Peso (tipo,peso);
       listaPeso.add(p);
    }
    
    public void agregarListaValor(Integer valor){
        listaValor.add(valor);
    }
    
    public float CalcularResultado(float resultado){
        //MODIFICAR LA SIGUIENTE LINEA, SOLO ESTÁ PUESTA PARA QUE COMPILE
        float multiplicacion;
        
        float p;
        int v;
        multiplicacion = 0;
        eFactor = 0;
//        for (int i=0; i < listaPeso.size(); i++) {
//            for (int j=0; j < listaValor.size();j++){
//                p = listaPeso.get(i).getPeso();
//                v = listaValor.get(j);
//               
//                multiplicacion = p * v;
//                eFactor = eFactor + multiplicacion;      
//            }
//        }
        for (int i=0; i<listaPeso.size();i++){
            p = listaPeso.get(i).getPeso();
            v = listaValor.get(i);
            System.out.print("P: "+p+" - ");
            System.out.print("V: "+v+" ");
            multiplicacion = p * v;
            System.out.println("Multip.: "+multiplicacion);
            eFactor = eFactor + multiplicacion;
        }
        resultado = eFactor;
        System.out.println("Resultado de calculo: " +resultado);
        return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Peso1textField = new javax.swing.JTextField();
        Peso2textField = new javax.swing.JTextField();
        Peso3textField = new javax.swing.JTextField();
        Peso4textField = new javax.swing.JTextField();
        Peso5textField = new javax.swing.JTextField();
        Peso6textField = new javax.swing.JTextField();
        Peso7textField = new javax.swing.JTextField();
        Peso8textField = new javax.swing.JTextField();
        RelevanciajComboBox01 = new javax.swing.JComboBox<>();
        RelevanciajComboBox02 = new javax.swing.JComboBox<>();
        RelevanciajComboBox03 = new javax.swing.JComboBox<>();
        RelevanciajComboBox04 = new javax.swing.JComboBox<>();
        RelevanciajComboBox05 = new javax.swing.JComboBox<>();
        RelevanciajComboBox06 = new javax.swing.JComboBox<>();
        RelevanciajComboBox07 = new javax.swing.JComboBox<>();
        RelevanciajComboBox08 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEFactor = new javax.swing.JTextField();
        txtEF = new javax.swing.JTextField();
        cargarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtRelevancia01 = new javax.swing.JTextField();
        txtRelevancia02 = new javax.swing.JTextField();
        txtRelevancia03 = new javax.swing.JTextField();
        txtRelevancia04 = new javax.swing.JTextField();
        txtRelevancia05 = new javax.swing.JTextField();
        txtRelevancia06 = new javax.swing.JTextField();
        txtRelevancia07 = new javax.swing.JTextField();
        txtRelevancia08 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factores de Complejidad Ambiental (EF)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Factor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Peso");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Relevancia");

        jLabel4.setText("1-Familiaridad con el modelo de proyecto utilizado");

        jLabel5.setText("2-Experiencia en la aplicación");

        jLabel6.setText("3-Experiencia en orientación a objetos");

        jLabel7.setText("4-Capacidad de analista líder");

        jLabel8.setText("5-Motivación");

        jLabel9.setText("6-Estabilidad de los requerimientos");

        jLabel10.setText("7-Personal part-time");

        jLabel11.setText("8-Dificultad del lenguaje de programación");

        Peso1textField.setPreferredSize(new java.awt.Dimension(40, 20));
        Peso1textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Peso1textFieldActionPerformed(evt);
            }
        });

        Peso2textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso3textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso4textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso5textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso6textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso7textField.setPreferredSize(new java.awt.Dimension(40, 20));

        Peso8textField.setPreferredSize(new java.awt.Dimension(40, 20));

        RelevanciajComboBox01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox01ActionPerformed(evt);
            }
        });

        RelevanciajComboBox02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox02ActionPerformed(evt);
            }
        });

        RelevanciajComboBox03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox03ActionPerformed(evt);
            }
        });

        RelevanciajComboBox04.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox04ActionPerformed(evt);
            }
        });

        RelevanciajComboBox05.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox05ActionPerformed(evt);
            }
        });

        RelevanciajComboBox06.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox06ActionPerformed(evt);
            }
        });

        RelevanciajComboBox07.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox07ActionPerformed(evt);
            }
        });

        RelevanciajComboBox08.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        RelevanciajComboBox08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelevanciajComboBox08ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("EFactor =");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("EF = 1.4 + (-0.03 * EFactor)");

        txtEFactor.setMinimumSize(new java.awt.Dimension(40, 20));
        txtEFactor.setPreferredSize(new java.awt.Dimension(40, 20));
        txtEFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEFactorActionPerformed(evt);
            }
        });

        txtEF.setMinimumSize(new java.awt.Dimension(40, 20));
        txtEF.setPreferredSize(new java.awt.Dimension(40, 20));

        cargarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cargarButton.setText("Cargar");
        cargarButton.setPreferredSize(new java.awt.Dimension(120, 25));
        cargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Salir");
        jButton3.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtRelevancia01.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia02.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia03.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia04.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia05.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia06.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia07.setPreferredSize(new java.awt.Dimension(40, 20));

        txtRelevancia08.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Peso1textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso2textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso3textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso4textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso5textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso6textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso7textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso8textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RelevanciajComboBox02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelevanciajComboBox08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRelevancia08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelevancia05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(40, 40, 40)
                .addComponent(txtEFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel13)
                .addGap(45, 45, 45)
                .addComponent(txtEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Peso1textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelevancia01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelevanciajComboBox01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Peso2textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelevancia02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelevanciajComboBox02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Peso3textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelevancia03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelevanciajComboBox03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtRelevancia04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso4textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelevanciajComboBox04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtRelevancia05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso5textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelevanciajComboBox05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RelevanciajComboBox06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtRelevancia06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso6textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RelevanciajComboBox07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtRelevancia07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso7textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RelevanciajComboBox08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtRelevancia08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Peso8textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Peso1textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Peso1textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Peso1textFieldActionPerformed

    private void txtEFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEFactorActionPerformed

    private void cargarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
            Peso1textField.setText(con2.consultarComplejidadAmbiental("E1"));
            agregarLista("E1",Float.parseFloat(Peso1textField.getText()));
            //System.out.println(Peso1textField.getText());

            Peso2textField.setText(con2.consultarComplejidadAmbiental("E2"));
            agregarLista("E2",Float.parseFloat(Peso2textField.getText()));
            //System.out.println(Peso2textField.getText());

            Peso3textField.setText(con2.consultarComplejidadAmbiental("E3"));
            agregarLista("E3",Float.parseFloat(Peso3textField.getText()));
            //System.out.println(Peso3textField.getText());

            Peso4textField.setText(con2.consultarComplejidadAmbiental("E4"));
            agregarLista("E4",Float.parseFloat(Peso4textField.getText()));
            //System.out.println(Peso4textField.getText());

            Peso5textField.setText(con2.consultarComplejidadAmbiental("E5"));
            agregarLista("E5",Float.parseFloat(Peso5textField.getText()));
            //System.out.println(Peso5textField.getText());

            Peso6textField.setText(con2.consultarComplejidadAmbiental("E6"));
            agregarLista("E6",Float.parseFloat(Peso6textField.getText()));
            //System.out.println(Peso6textField.getText());

            Peso7textField.setText(con2.consultarComplejidadAmbiental("E7"));
            agregarLista("E7",Float.parseFloat(Peso7textField.getText()));
            //System.out.println(Peso7textField.getText());

            Peso8textField.setText(con2.consultarComplejidadAmbiental("E8"));
            agregarLista("E8",Float.parseFloat(Peso8textField.getText()));
            //System.out.println(Peso8textField.getText());

        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RelevanciajComboBox01ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia01.setText(con2.consultarRelevancia(RelevanciajComboBox01.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia01.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox02ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia02.setText(con2.consultarRelevancia(RelevanciajComboBox02.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia02.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox03ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia03.setText(con2.consultarRelevancia(RelevanciajComboBox03.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia03.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox04ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia04.setText(con2.consultarRelevancia(RelevanciajComboBox04.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia04.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox05ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia05.setText(con2.consultarRelevancia(RelevanciajComboBox05.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia05.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox06ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia06.setText(con2.consultarRelevancia(RelevanciajComboBox06.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia06.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox07ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia07.setText(con2.consultarRelevancia(RelevanciajComboBox07.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia07.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void RelevanciajComboBox08ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        try {
            txtRelevancia08.setText(con2.consultarRelevancia(RelevanciajComboBox08.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia08.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_ambiental.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        agregarListaValor(Integer.parseInt(txtRelevancia01.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia02.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia03.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia04.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia05.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia06.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia07.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia08.getText()));
        
        for (int j=0; j < listaValor.size();j++){
            System.out.println(listaValor.get(j));
        }
        float eFactor2 = 0;
        float tf = 0;
        eFactor2 = this.CalcularResultado(eFactor2);
        txtEFactor.setText(Float.toString(eFactor2));
        
        tf = (float) (1.4 + ((-0.03) * eFactor2));
        txtEF.setText(Float.toString(tf));
    }                                        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Peso1textField;
    private javax.swing.JTextField Peso2textField;
    private javax.swing.JTextField Peso3textField;
    private javax.swing.JTextField Peso4textField;
    private javax.swing.JTextField Peso5textField;
    private javax.swing.JTextField Peso6textField;
    private javax.swing.JTextField Peso7textField;
    private javax.swing.JTextField Peso8textField;
    private javax.swing.JComboBox<String> RelevanciajComboBox01;
    private javax.swing.JComboBox<String> RelevanciajComboBox02;
    private javax.swing.JComboBox<String> RelevanciajComboBox03;
    private javax.swing.JComboBox<String> RelevanciajComboBox04;
    private javax.swing.JComboBox<String> RelevanciajComboBox05;
    private javax.swing.JComboBox<String> RelevanciajComboBox06;
    private javax.swing.JComboBox<String> RelevanciajComboBox07;
    private javax.swing.JComboBox<String> RelevanciajComboBox08;
    private javax.swing.JButton cargarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEF;
    private javax.swing.JTextField txtEFactor;
    private javax.swing.JTextField txtRelevancia01;
    private javax.swing.JTextField txtRelevancia02;
    private javax.swing.JTextField txtRelevancia03;
    private javax.swing.JTextField txtRelevancia04;
    private javax.swing.JTextField txtRelevancia05;
    private javax.swing.JTextField txtRelevancia06;
    private javax.swing.JTextField txtRelevancia07;
    private javax.swing.JTextField txtRelevancia08;
    // End of variables declaration//GEN-END:variables
}
