/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

/**
 *
 * @author Cristian
 */
public class frm_esfuerzo extends javax.swing.JInternalFrame {
    float puntoDeCasoDeUsoAjustado;
    int CF1, CF2;
    
    /**
     * Creates new form frm_esfuerzo
     */
    public frm_esfuerzo() {
        initComponents();
    }

    public frm_esfuerzo(float puntoDeCasoDeUsoAjustado, int CF1, int CF2) {
        initComponents();
        this.puntoDeCasoDeUsoAjustado = puntoDeCasoDeUsoAjustado;
        this.CF1 = CF1;
        this.CF2 = CF2;
        //edición campos de txt
        System.out.println(this.getPuntoDeCasoDeUsoAjustado());
        this.txtUCP.setText(Float.toString(this.getPuntoDeCasoDeUsoAjustado()));
    }

    public float calcularEsfuerzo (float UCP, int CF1, int CF2){
        //Calculo de CF
        int CF = CF1 + CF2;
        int aux=0;
        if (CF <= 2){
            aux=20;
        }
        if (CF==3 | CF==4){
            aux=28;
        }
        if(CF >= 5){
            aux=36;
        }
        this.txtCF.setText(Integer.toString(aux));
        return UCP * aux;//
    }

    public float getPuntoDeCasoDeUsoAjustado() {
        return puntoDeCasoDeUsoAjustado;
    }

    public void setPuntoDeCasoDeUsoAjustado(float puntoDeCasoDeUsoAjustado) {
        this.puntoDeCasoDeUsoAjustado = puntoDeCasoDeUsoAjustado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        txtUCP = new javax.swing.JTextField();
        txtCF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calcularButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Esfuerzo Horas-Hombre (E)");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("E     =   UCP     X    CF");

        txtE.setMinimumSize(new java.awt.Dimension(59, 20));
        txtE.setPreferredSize(new java.awt.Dimension(80, 20));

        txtUCP.setMinimumSize(new java.awt.Dimension(59, 20));
        txtUCP.setPreferredSize(new java.awt.Dimension(80, 20));

        txtCF.setMinimumSize(new java.awt.Dimension(59, 20));
        txtCF.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel2.setText("=");

        jLabel3.setText("X");

        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.setPreferredSize(new java.awt.Dimension(71, 23));
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(txtUCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(calcularButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularButton)
                    .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        float E;
        E = this.calcularEsfuerzo(this.puntoDeCasoDeUsoAjustado, CF1, CF2);
        this.txtE.setText(Float.toString(E));
    }//GEN-LAST:event_calcularButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField txtCF;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtUCP;
    // End of variables declaration//GEN-END:variables
}
