/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

import classes.Peso;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.conexionsql;

/**
 *
 * @author Mari
 */
public class frm_complejidad_tecnica extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_complejidad_tecnica
     */
    conexionsql con2 = new conexionsql();
    ArrayList<Peso> listaPeso  = new ArrayList<>();
    ArrayList <Integer> listaValor = new ArrayList<>();
    float tFactor;
    float TCF;
    
    public frm_complejidad_tecnica() {
        initComponents();
        con2.conectarCU();
    }

    public float getTCF() {
        return TCF;
    }

    public void setTCF(float TCF) {
        this.TCF = TCF;
    }
    
    public void agregarLista(String tipo, float peso){
       Peso p = new Peso (tipo,peso);
       listaPeso.add(p);
    }
    
    public void agregarListaValor(Integer valor){
        listaValor.add(valor);
        
    }
    
    public float CalcularResultado(float resultado){
       float multiplicacion;
        
       float p;
       int v;
       multiplicacion = 0;
       tFactor = 0;
//       for (int i=0; i < listaPeso.size(); i++) {
//           for (int j=0; j < listaValor.size();j++){
//               p = listaPeso.get(i).getPeso();
//               v = listaValor.get(j);
//               
//             multiplicacion = p * v;
//             tFactor = tFactor + multiplicacion;      
//           }   
//       }
        for (int i=0; i < listaPeso.size(); i++) {
            p = listaPeso.get(i).getPeso();
            v = listaValor.get(i);
            multiplicacion = p * v;
            tFactor = tFactor + multiplicacion;         
        }
        resultado = tFactor;
        return resultado;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbRelevancia01 = new javax.swing.JComboBox<>();
        txtRelevancia01 = new javax.swing.JTextField();
        btnCalcularFactores = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRelevancia02 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRelevancia03 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRelevancia04 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRelevancia05 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRelevancia06 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbRelevancia08 = new javax.swing.JComboBox<>();
        cmbRelevancia09 = new javax.swing.JComboBox<>();
        cmbRelevancia10 = new javax.swing.JComboBox<>();
        cmbRelevancia11 = new javax.swing.JComboBox<>();
        cmbRelevancia12 = new javax.swing.JComboBox<>();
        cmbRelevancia13 = new javax.swing.JComboBox<>();
        txtRelevancia13 = new javax.swing.JTextField();
        txtRelevancia12 = new javax.swing.JTextField();
        txtRelevancia11 = new javax.swing.JTextField();
        txtRelevancia10 = new javax.swing.JTextField();
        txtRelevancia09 = new javax.swing.JTextField();
        txtRelevancia08 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRelevancia07 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTCF = new javax.swing.JTextField();
        txtFactor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cmbRelevancia02 = new javax.swing.JComboBox<>();
        cmbRelevancia03 = new javax.swing.JComboBox<>();
        cmbRelevancia04 = new javax.swing.JComboBox<>();
        cmbRelevancia05 = new javax.swing.JComboBox<>();
        cmbRelevancia07 = new javax.swing.JComboBox<>();
        cmbRelevancia06 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        textPeso02 = new javax.swing.JTextField();
        textPeso03 = new javax.swing.JTextField();
        textPeso04 = new javax.swing.JTextField();
        textPeso05 = new javax.swing.JTextField();
        textPeso06 = new javax.swing.JTextField();
        textPeso01 = new javax.swing.JTextField();
        textPeso07 = new javax.swing.JTextField();
        textPeso08 = new javax.swing.JTextField();
        textPeso09 = new javax.swing.JTextField();
        textPeso10 = new javax.swing.JTextField();
        textPeso11 = new javax.swing.JTextField();
        textPeso12 = new javax.swing.JTextField();
        textPeso13 = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factores de Complejidad Técnica (TCF)");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbRelevancia01.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia01ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia01, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, 40));

        txtRelevancia01.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia01, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 70, 40));

        btnCalcularFactores.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularFactores.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCalcularFactores.setText("Calcular");
        btnCalcularFactores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFactoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularFactores, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 210, 50));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 130, 50));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Relevancia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 40));

        jLabel1.setText("8 - Portabilidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 200, 40));

        jLabel2.setText("1 - Sistema distribuido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 40));

        jLabel3.setText("2 -Objetivos de performance o tiempo de respuesta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 40));

        txtRelevancia02.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia02, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 70, 40));

        jLabel4.setText("3 - Eficiencia de usuario final");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 40));

        txtRelevancia03.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia03, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 70, 40));

        jLabel5.setText("4 - Procesamiento interno complejo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 40));

        txtRelevancia04.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia04, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 70, 40));

        jLabel6.setText("5 - El código debe ser reutilizable");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 40));

        txtRelevancia05.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia05, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 70, 40));

        jLabel8.setText("6 - Facilidad de instalación");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 40));

        txtRelevancia06.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia06, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 70, 40));

        jLabel10.setText("7 - Facilidad de uso");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 260, 40));

        jLabel11.setText("9 - Facilidad de cambio");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 200, 40));

        jLabel13.setText("10 - Concurrencia");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 200, 40));

        jLabel15.setText("11 - Incluye objetivos especiales de  seguridad");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 280, 40));

        jLabel16.setText("12 - Provee acceso directo a terceras partes");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 270, 40));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("13 - Se requiere facilidades especiales de entrenamiento a usuario");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 400, 30));

        cmbRelevancia08.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia08.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia08ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia08, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 120, 40));

        cmbRelevancia09.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia09ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia09, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, 120, 40));

        cmbRelevancia10.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia10ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 120, 40));

        cmbRelevancia11.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia11ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 120, 40));

        cmbRelevancia12.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia12ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 330, 120, 40));

        cmbRelevancia13.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia13ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 120, 40));

        txtRelevancia13.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 70, 40));

        txtRelevancia12.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 330, 70, 40));

        txtRelevancia11.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 280, 70, 40));

        txtRelevancia10.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 230, 70, 40));

        txtRelevancia09.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia09.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia09, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 180, 70, 40));

        txtRelevancia08.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia08, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 130, 70, 40));

        jLabel19.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Relevancia");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, 40));

        jLabel20.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Factor ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 139, 48));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Factor ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 139, 48));

        txtRelevancia07.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtRelevancia07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRelevancia07, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 80, 70, 40));

        jLabel22.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("TCF = 0.6 + (0.01 * TFactor)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 230, 48));

        txtTCF.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtTCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 70, 40));

        txtFactor.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtFactor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 70, 40));

        jLabel23.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("TFactor = ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 48));

        cmbRelevancia02.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia02ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia02, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, 40));

        cmbRelevancia03.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia03ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia03, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 40));

        cmbRelevancia04.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia04.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia04ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia04, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, 40));

        cmbRelevancia05.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia05.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia05ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia05, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 120, 40));

        cmbRelevancia07.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia07.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia07ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia07, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 120, 40));

        cmbRelevancia06.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        cmbRelevancia06.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Irrelevante", "Baja", "Moderada", "Promedio", "Significativa", "Esencial" }));
        cmbRelevancia06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelevancia06ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRelevancia06, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 120, 40));

        jLabel18.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Peso");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, 30));

        textPeso02.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 70, 40));

        textPeso03.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 70, 40));

        textPeso04.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso04, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 70, 40));

        textPeso05.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso05, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 70, 40));

        textPeso06.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso06, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 70, 40));

        textPeso01.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 70, 40));

        textPeso07.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso07, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 70, 40));

        textPeso08.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso08, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 70, 40));

        textPeso09.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso09.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso09, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 70, 40));

        textPeso10.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 70, 40));

        textPeso11.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 70, 40));

        textPeso12.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 70, 40));

        textPeso13.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textPeso13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textPeso13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 70, 40));

        btnCargar.setBackground(new java.awt.Color(255, 255, 255));
        btnCargar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        try {
            textPeso01.setText(con2.consultarComplejidadTecnica("T1"));
            agregarLista("T1",Float.parseFloat(textPeso01.getText()));

            textPeso02.setText(con2.consultarComplejidadTecnica("T2"));
            agregarLista("T2",Float.parseFloat(textPeso02.getText()));

            textPeso03.setText(con2.consultarComplejidadTecnica("T3"));
            agregarLista("T3",Float.parseFloat(textPeso03.getText()));

            textPeso04.setText(con2.consultarComplejidadTecnica("T4"));
            agregarLista("T4",Float.parseFloat(textPeso04.getText()));

            textPeso05.setText(con2.consultarComplejidadTecnica("T5"));
            agregarLista("T5",Float.parseFloat(textPeso05.getText()));

            textPeso06.setText(con2.consultarComplejidadTecnica("T6"));
            agregarLista("T6",Float.parseFloat(textPeso06.getText()));

            textPeso07.setText(con2.consultarComplejidadTecnica("T7"));
            agregarLista("T7",Float.parseFloat(textPeso07.getText()));

            textPeso08.setText(con2.consultarComplejidadTecnica("T8"));
            agregarLista("T8",Float.parseFloat(textPeso08.getText()));

            textPeso09.setText(con2.consultarComplejidadTecnica("T9"));
            agregarLista("T9",Float.parseFloat(textPeso09.getText()));

            textPeso10.setText(con2.consultarComplejidadTecnica("T10"));
            agregarLista("T10",Float.parseFloat(textPeso10.getText()));

            textPeso11.setText(con2.consultarComplejidadTecnica("T11"));
            agregarLista("T11",Float.parseFloat(textPeso11.getText()));

            textPeso12.setText(con2.consultarComplejidadTecnica("T12"));
            agregarLista("T12",Float.parseFloat(textPeso12.getText()));

            textPeso13.setText(con2.consultarComplejidadTecnica("T13"));
            agregarLista("T13",Float.parseFloat(textPeso13.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void cmbRelevancia06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia06ActionPerformed
        try {
            txtRelevancia06.setText(con2.consultarRelevancia(cmbRelevancia06.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia06.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia06ActionPerformed

    private void cmbRelevancia07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia07ActionPerformed

        try {
            txtRelevancia07.setText(con2.consultarRelevancia(cmbRelevancia07.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia07.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia07ActionPerformed

    private void cmbRelevancia05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia05ActionPerformed
        try {
            txtRelevancia05.setText(con2.consultarRelevancia(cmbRelevancia05.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia05.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia05ActionPerformed

    private void cmbRelevancia04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia04ActionPerformed
        try {
            txtRelevancia04.setText(con2.consultarRelevancia(cmbRelevancia04.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia04.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia04ActionPerformed

    private void cmbRelevancia03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia03ActionPerformed
        try {
            txtRelevancia03.setText(con2.consultarRelevancia(cmbRelevancia03.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia03.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia03ActionPerformed

    private void cmbRelevancia02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia02ActionPerformed
        try {
            txtRelevancia02.setText(con2.consultarRelevancia(cmbRelevancia02.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia02.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia02ActionPerformed

    private void cmbRelevancia13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia13ActionPerformed
        try {
            txtRelevancia13.setText(con2.consultarRelevancia(cmbRelevancia13.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia13.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia13ActionPerformed

    private void cmbRelevancia12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia12ActionPerformed
        try {
            txtRelevancia12.setText(con2.consultarRelevancia(cmbRelevancia12.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia12.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia12ActionPerformed

    private void cmbRelevancia11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia11ActionPerformed
        try {
            txtRelevancia11.setText(con2.consultarRelevancia(cmbRelevancia11.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia11.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia11ActionPerformed

    private void cmbRelevancia10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia10ActionPerformed
        try {
            txtRelevancia10.setText(con2.consultarRelevancia(cmbRelevancia10.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia10.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia10ActionPerformed

    private void cmbRelevancia09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia09ActionPerformed
        try {
            txtRelevancia09.setText(con2.consultarRelevancia(cmbRelevancia09.getSelectedItem().toString()));     
            //agregarListaValor(Integer.parseInt(txtRelevancia09.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia09ActionPerformed

    private void cmbRelevancia08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia08ActionPerformed
        try {
            txtRelevancia08.setText(con2.consultarRelevancia(cmbRelevancia08.getSelectedItem().toString()));
            //agregarListaValor(Integer.parseInt(txtRelevancia08.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia08ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularFactoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFactoresActionPerformed
        //Carga del Array ListaValor
        agregarListaValor(Integer.parseInt(txtRelevancia01.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia02.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia03.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia04.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia05.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia06.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia07.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia08.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia09.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia10.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia11.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia12.getText()));
        agregarListaValor(Integer.parseInt(txtRelevancia13.getText()));
        //Final de Carga del Array ListaValor
        float tFactor2 = 0;
        //float tcf = 0;
        tFactor2=CalcularResultado(tFactor2);
        
        txtFactor.setText(Float.toString(tFactor2));
        
        setTCF((float) (0.6 + (0.01 * tFactor2)));
        txtTCF.setText(Float.toString(this.getTCF()));
    }//GEN-LAST:event_btnCalcularFactoresActionPerformed

    private void cmbRelevancia01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelevancia01ActionPerformed
        try {
            txtRelevancia01.setText(con2.consultarRelevancia((cmbRelevancia01.getSelectedItem().toString())));
            //agregarListaValor(Integer.parseInt(txtRelevancia01.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_complejidad_tecnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbRelevancia01ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularFactores;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbRelevancia01;
    private javax.swing.JComboBox<String> cmbRelevancia02;
    private javax.swing.JComboBox<String> cmbRelevancia03;
    private javax.swing.JComboBox<String> cmbRelevancia04;
    private javax.swing.JComboBox<String> cmbRelevancia05;
    private javax.swing.JComboBox<String> cmbRelevancia06;
    private javax.swing.JComboBox<String> cmbRelevancia07;
    private javax.swing.JComboBox<String> cmbRelevancia08;
    private javax.swing.JComboBox<String> cmbRelevancia09;
    private javax.swing.JComboBox<String> cmbRelevancia10;
    private javax.swing.JComboBox<String> cmbRelevancia11;
    private javax.swing.JComboBox<String> cmbRelevancia12;
    private javax.swing.JComboBox<String> cmbRelevancia13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textPeso01;
    private javax.swing.JTextField textPeso02;
    private javax.swing.JTextField textPeso03;
    private javax.swing.JTextField textPeso04;
    private javax.swing.JTextField textPeso05;
    private javax.swing.JTextField textPeso06;
    private javax.swing.JTextField textPeso07;
    private javax.swing.JTextField textPeso08;
    private javax.swing.JTextField textPeso09;
    private javax.swing.JTextField textPeso10;
    private javax.swing.JTextField textPeso11;
    private javax.swing.JTextField textPeso12;
    private javax.swing.JTextField textPeso13;
    private javax.swing.JTextField txtFactor;
    private javax.swing.JTextField txtRelevancia01;
    private javax.swing.JTextField txtRelevancia02;
    private javax.swing.JTextField txtRelevancia03;
    private javax.swing.JTextField txtRelevancia04;
    private javax.swing.JTextField txtRelevancia05;
    private javax.swing.JTextField txtRelevancia06;
    private javax.swing.JTextField txtRelevancia07;
    private javax.swing.JTextField txtRelevancia08;
    private javax.swing.JTextField txtRelevancia09;
    private javax.swing.JTextField txtRelevancia10;
    private javax.swing.JTextField txtRelevancia11;
    private javax.swing.JTextField txtRelevancia12;
    private javax.swing.JTextField txtRelevancia13;
    private javax.swing.JTextField txtTCF;
    // End of variables declaration//GEN-END:variables
}
