/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.casouso;

import classes.Factor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql.conexionsql;

/**
 *
 * @author Mari
 */
public class frm_peso_cu extends javax.swing.JInternalFrame {

     ArrayList<Factor> lista  = new ArrayList<>();
     Integer cuSinAjustar = 0;
     conexionsql con2 = new conexionsql();
     
    public frm_peso_cu() {
        initComponents();
        con2.conectarCU();
    }
    
    public Integer getValorCuSinAjustar()
    {
        return cuSinAjustar;
    }
    
     private void limpiar() {
        cmbTransacciones.setSelectedItem(0);
        textTrans.setText(null);
        txtTrans.setText(null);
        cmbClases.setSelectedItem(0);
        textClases.setText(null);
        txtClas.setText(null);
    }
    public void CalcularResultado(){
     int multiplicacion;
        
       int val;
       int fact;
       multiplicacion = 0;
       cuSinAjustar = 0;
       for (int i=0; i < lista.size(); i++){
          
           
           val =lista.get(i).getValor(); 
           fact = lista.get(i).getFactor();
           
           multiplicacion = val * fact;
           
           jTextArea1.append("\n");
           jTextArea1.append(lista.get(i).getTipo() + ": " + val + " x " + fact + " = " + multiplicacion + "\n");
           
           cuSinAjustar = cuSinAjustar + multiplicacion;
       }
        jTextArea1.append("TOTAL: " + cuSinAjustar + "\n");
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCalculo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        textTrans = new javax.swing.JTextField();
        cmbTransacciones = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTrans = new javax.swing.JTextField();
        btnOKTrans = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        btnCalculo1 = new javax.swing.JButton();
        textClases = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbClases = new javax.swing.JComboBox<>();
        txtClas = new javax.swing.JTextField();
        btnOKClas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Factor de peso de CU sin ajustar (UUCW)");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(700, 800));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 530, 250));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 120, 40));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 120, 40));

        btnCalculo.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculo.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCalculo.setText("Calcular");
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 133, 41));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setPreferredSize(new java.awt.Dimension(700, 800));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 530, 250));

        textTrans.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textTrans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTransActionPerformed(evt);
            }
        });
        jPanel2.add(textTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 69, 39));

        cmbTransacciones.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cmbTransacciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Medio", "Complejo" }));
        cmbTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTransaccionesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, 40));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Factor");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, 40));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Transacciones");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 40));

        txtTrans.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtTrans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransActionPerformed(evt);
            }
        });
        jPanel2.add(txtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 40));

        btnOKTrans.setBackground(new java.awt.Color(255, 255, 255));
        btnOKTrans.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnOKTrans.setText("OK");
        btnOKTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKTransActionPerformed(evt);
            }
        });
        jPanel2.add(btnOKTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 80, -1, 41));

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 120, 40));

        btnReset1.setBackground(new java.awt.Color(255, 255, 255));
        btnReset1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 120, 40));

        btnCalculo1.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculo1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCalculo1.setText("Calcular");
        btnCalculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculo1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 133, 41));

        textClases.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        textClases.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(textClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 69, 39));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Clases");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 40));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Factor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, 40));

        cmbClases.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cmbClases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Medio", "Complejo" }));
        cmbClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClasesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 40));

        txtClas.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        txtClas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClasActionPerformed(evt);
            }
        });
        jPanel2.add(txtClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, 40));

        btnOKClas.setBackground(new java.awt.Color(255, 255, 255));
        btnOKClas.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnOKClas.setText("OK");
        btnOKClas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKClasActionPerformed(evt);
            }
        });
        jPanel2.add(btnOKClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 41));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClasesActionPerformed
        try {
            txtClas.setText(con2.consultarClases(cmbClases.getSelectedItem().toString()));
        } catch (SQLException ex) {
            Logger.getLogger(frm_actores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbClasesActionPerformed

    private void txtClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClasActionPerformed

    private void btnOKClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKClasActionPerformed
        if ( !"".equals(cmbClases.getSelectedItem().toString()) && !"".equals(textClases.getText()) && !"".equals(txtClas.getText()) ){
            jTextArea1.append("CLASES DE ANÁLISIS"+ "\n");
            jTextArea1.append(cmbClases.getSelectedItem().toString() + ": " + textClases.getText() + " x " + txtClas.getText() +"\n");

            String tipo = cmbClases.getSelectedItem().toString();
            int v = Integer.parseInt(textClases.getText());
            int f = Integer.parseInt(txtClas.getText());

            Factor factor = new Factor (tipo,v,f);
            lista.add(factor);

            this.limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los valores", "Atención", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        }
    }//GEN-LAST:event_btnOKClasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.limpiar();
        jTextArea1.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed
        CalcularResultado();
    }//GEN-LAST:event_btnCalculoActionPerformed

    private void cmbTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTransaccionesActionPerformed
       try {              
              txtTrans.setText(con2.consultarTransacciones(cmbTransacciones.getSelectedItem().toString()));
         } catch (SQLException ex) {
             Logger.getLogger(frm_actores.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_cmbTransaccionesActionPerformed

    private void txtTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransActionPerformed

    private void btnOKTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKTransActionPerformed
        if ( !"".equals(cmbTransacciones.getSelectedItem().toString()) && !"".equals(textTrans.getText()) && !"".equals(txtTrans.getText()) ){
            jTextArea1.append("TRANSACCIONES"+ "\n");
            jTextArea1.append(cmbTransacciones.getSelectedItem().toString() + ": " + textTrans.getText() + " x " + txtTrans.getText() +"\n");

            String tipo = cmbTransacciones.getSelectedItem().toString();
            int v = Integer.parseInt(textTrans.getText());
            int f = Integer.parseInt(txtTrans.getText());

            Factor factor = new Factor (tipo,v,f);
            lista.add(factor);

            this.limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los valores", "Atención", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnOKTransActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        this.limpiar();
        jTextArea1.setText(null);
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnCalculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculo1ActionPerformed

    
    private void textTransActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculo;
    private javax.swing.JButton btnCalculo1;
    private javax.swing.JButton btnOKClas;
    private javax.swing.JButton btnOKTrans;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbClases;
    private javax.swing.JComboBox<String> cmbTransacciones;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField textClases;
    private javax.swing.JTextField textTrans;
    private javax.swing.JTextField txtClas;
    private javax.swing.JTextField txtTrans;
    // End of variables declaration//GEN-END:variables
}
